name: Set GitHub Actions style version tags

on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on:
      group: nyt-runners
      labels: nyt-2-core
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: true
